[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.virtualenv"]

[phases.install]
cmds = [
  "python3 -m venv venv",
  "source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "source venv/bin/activate && cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
